// Code generated by protoc-gen-go.
// source: proto/tytera/tytera.proto
// DO NOT EDIT!

/*
Package tytera is a generated protocol buffer package.

It is generated from these files:
	proto/tytera/tytera.proto

It has these top-level messages:
	TyteraCodeplug
	BasicInformation
	GeneralSettings
	MenuItems
	ContactsMenu
	CallLogMenu
	ScanMenu
	UtilitiesMenu
	OneTouchAccessEntry
	ButtonDefinitions
	MessagePresets
	PrivacySettings
	EmergencySystemEntry
	EmergencySystems
	ContactEntry
	Contacts
	RxGroupEntry
	RxGroups
*/
package tytera

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RadioBand int32

const (
	RadioBand_VHF_136_174 RadioBand = 0
	RadioBand_UHF_350_400 RadioBand = 1
	RadioBand_UHF_400_480 RadioBand = 2
	RadioBand_UHF_450_520 RadioBand = 3
	RadioBand_DISABLED    RadioBand = 255
)

var RadioBand_name = map[int32]string{
	0:   "VHF_136_174",
	1:   "UHF_350_400",
	2:   "UHF_400_480",
	3:   "UHF_450_520",
	255: "DISABLED",
}
var RadioBand_value = map[string]int32{
	"VHF_136_174": 0,
	"UHF_350_400": 1,
	"UHF_400_480": 2,
	"UHF_450_520": 3,
	"DISABLED":    255,
}

func (x RadioBand) String() string {
	return proto.EnumName(RadioBand_name, int32(x))
}
func (RadioBand) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MonitorType int32

const (
	MonitorType_SILENT       MonitorType = 0
	MonitorType_OPEN_SQUELCH MonitorType = 1
)

var MonitorType_name = map[int32]string{
	0: "SILENT",
	1: "OPEN_SQUELCH",
}
var MonitorType_value = map[string]int32{
	"SILENT":       0,
	"OPEN_SQUELCH": 1,
}

func (x MonitorType) String() string {
	return proto.EnumName(MonitorType_name, int32(x))
}
func (MonitorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SystemType int32

const (
	SystemType_NONE    SystemType = 0
	SystemType_DIGITAL SystemType = 1
	SystemType_ANALOG  SystemType = 2
	SystemType_BOTH    SystemType = 3
)

var SystemType_name = map[int32]string{
	0: "NONE",
	1: "DIGITAL",
	2: "ANALOG",
	3: "BOTH",
}
var SystemType_value = map[string]int32{
	"NONE":    0,
	"DIGITAL": 1,
	"ANALOG":  2,
	"BOTH":    3,
}

func (x SystemType) String() string {
	return proto.EnumName(SystemType_name, int32(x))
}
func (SystemType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type IntroScreenMode int32

const (
	IntroScreenMode_CHAR_STRING IntroScreenMode = 0
	IntroScreenMode_PICTURE     IntroScreenMode = 1
)

var IntroScreenMode_name = map[int32]string{
	0: "CHAR_STRING",
	1: "PICTURE",
}
var IntroScreenMode_value = map[string]int32{
	"CHAR_STRING": 0,
	"PICTURE":     1,
}

func (x IntroScreenMode) String() string {
	return proto.EnumName(IntroScreenMode_name, int32(x))
}
func (IntroScreenMode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type OperationMode int32

const (
	OperationMode_MR      OperationMode = 0
	OperationMode_CHANNEL OperationMode = 255
)

var OperationMode_name = map[int32]string{
	0:   "MR",
	255: "CHANNEL",
}
var OperationMode_value = map[string]int32{
	"MR":      0,
	"CHANNEL": 255,
}

func (x OperationMode) String() string {
	return proto.EnumName(OperationMode_name, int32(x))
}
func (OperationMode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ButtonFunction int32

const (
	ButtonFunction_UNASSIGNED            ButtonFunction = 0
	ButtonFunction_ALL_ALERT_TONES_ONOFF ButtonFunction = 1
	ButtonFunction_EMERGENCY_ON          ButtonFunction = 2
	ButtonFunction_EMERGENCY_OFF         ButtonFunction = 3
	ButtonFunction_HIGH_LOW_POWER        ButtonFunction = 4
	ButtonFunction_MONITOR               ButtonFunction = 5
	ButtonFunction_NUISANCE_DELETE       ButtonFunction = 6
	ButtonFunction_ONE_TOUCH_ACCESS_1    ButtonFunction = 7
	ButtonFunction_ONE_TOUCH_ACCESS_2    ButtonFunction = 8
	ButtonFunction_ONE_TOUCH_ACCESS_3    ButtonFunction = 9
	ButtonFunction_ONE_TOUCH_ACCESS_4    ButtonFunction = 10
	ButtonFunction_ONE_TOUCH_ACCESS_5    ButtonFunction = 11
	ButtonFunction_ONE_TOUCH_ACCESS_6    ButtonFunction = 12
	ButtonFunction_REPEATER_TALKAROUND   ButtonFunction = 13
	ButtonFunction_SCAN_ONOFF            ButtonFunction = 14
	ButtonFunction_TIGHT_NORMAL_SQUELCH  ButtonFunction = 21
	ButtonFunction_PRIVACY_ONOFF         ButtonFunction = 22
	ButtonFunction_VOX_ONOFF             ButtonFunction = 23
	ButtonFunction_ZONE_TOGGLE           ButtonFunction = 25
	ButtonFunction_BATTERY_INDICATOR     ButtonFunction = 26
	ButtonFunction_MANUAL_DIAL           ButtonFunction = 30
	ButtonFunction_LONE_WORK_ONOFF       ButtonFunction = 31
	ButtonFunction_TONE_1750HZ           ButtonFunction = 38
)

var ButtonFunction_name = map[int32]string{
	0:  "UNASSIGNED",
	1:  "ALL_ALERT_TONES_ONOFF",
	2:  "EMERGENCY_ON",
	3:  "EMERGENCY_OFF",
	4:  "HIGH_LOW_POWER",
	5:  "MONITOR",
	6:  "NUISANCE_DELETE",
	7:  "ONE_TOUCH_ACCESS_1",
	8:  "ONE_TOUCH_ACCESS_2",
	9:  "ONE_TOUCH_ACCESS_3",
	10: "ONE_TOUCH_ACCESS_4",
	11: "ONE_TOUCH_ACCESS_5",
	12: "ONE_TOUCH_ACCESS_6",
	13: "REPEATER_TALKAROUND",
	14: "SCAN_ONOFF",
	21: "TIGHT_NORMAL_SQUELCH",
	22: "PRIVACY_ONOFF",
	23: "VOX_ONOFF",
	25: "ZONE_TOGGLE",
	26: "BATTERY_INDICATOR",
	30: "MANUAL_DIAL",
	31: "LONE_WORK_ONOFF",
	38: "TONE_1750HZ",
}
var ButtonFunction_value = map[string]int32{
	"UNASSIGNED":            0,
	"ALL_ALERT_TONES_ONOFF": 1,
	"EMERGENCY_ON":          2,
	"EMERGENCY_OFF":         3,
	"HIGH_LOW_POWER":        4,
	"MONITOR":               5,
	"NUISANCE_DELETE":       6,
	"ONE_TOUCH_ACCESS_1":    7,
	"ONE_TOUCH_ACCESS_2":    8,
	"ONE_TOUCH_ACCESS_3":    9,
	"ONE_TOUCH_ACCESS_4":    10,
	"ONE_TOUCH_ACCESS_5":    11,
	"ONE_TOUCH_ACCESS_6":    12,
	"REPEATER_TALKAROUND":   13,
	"SCAN_ONOFF":            14,
	"TIGHT_NORMAL_SQUELCH":  21,
	"PRIVACY_ONOFF":         22,
	"VOX_ONOFF":             23,
	"ZONE_TOGGLE":           25,
	"BATTERY_INDICATOR":     26,
	"MANUAL_DIAL":           30,
	"LONE_WORK_ONOFF":       31,
	"TONE_1750HZ":           38,
}

func (x ButtonFunction) String() string {
	return proto.EnumName(ButtonFunction_name, int32(x))
}
func (ButtonFunction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type OneTouchCallType int32

const (
	// Mode = none
	OneTouchCallType_NO_CALL_TYPE OneTouchCallType = 0
	// Mode = analog
	OneTouchCallType_DTMF1 OneTouchCallType = 1
	OneTouchCallType_DTMF2 OneTouchCallType = 2
	OneTouchCallType_DTMF3 OneTouchCallType = 3
	OneTouchCallType_DTMF4 OneTouchCallType = 4
	// Mode = digital
	OneTouchCallType_CALL         OneTouchCallType = 101
	OneTouchCallType_TEXT_MESSAGE OneTouchCallType = 102
)

var OneTouchCallType_name = map[int32]string{
	0:   "NO_CALL_TYPE",
	1:   "DTMF1",
	2:   "DTMF2",
	3:   "DTMF3",
	4:   "DTMF4",
	101: "CALL",
	102: "TEXT_MESSAGE",
}
var OneTouchCallType_value = map[string]int32{
	"NO_CALL_TYPE": 0,
	"DTMF1":        1,
	"DTMF2":        2,
	"DTMF3":        3,
	"DTMF4":        4,
	"CALL":         101,
	"TEXT_MESSAGE": 102,
}

func (x OneTouchCallType) String() string {
	return proto.EnumName(OneTouchCallType_name, int32(x))
}
func (OneTouchCallType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

//
// ------------------
// Emergency Systems
// ------------------
// https://github.com/yeyus/md380-webtools/wiki/MD389---Digit-Emergency-System
type AlarmType int32

const (
	AlarmType_DISABLED_TYPE          AlarmType = 0
	AlarmType_REGULAR_TYPE           AlarmType = 1
	AlarmType_SILENT_TYPE            AlarmType = 2
	AlarmType_SILENT_WITH_VOICE_TYPE AlarmType = 3
)

var AlarmType_name = map[int32]string{
	0: "DISABLED_TYPE",
	1: "REGULAR_TYPE",
	2: "SILENT_TYPE",
	3: "SILENT_WITH_VOICE_TYPE",
}
var AlarmType_value = map[string]int32{
	"DISABLED_TYPE":          0,
	"REGULAR_TYPE":           1,
	"SILENT_TYPE":            2,
	"SILENT_WITH_VOICE_TYPE": 3,
}

func (x AlarmType) String() string {
	return proto.EnumName(AlarmType_name, int32(x))
}
func (AlarmType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type AlarmMode int32

const (
	AlarmMode_EMERGENCY_ALARM                      AlarmMode = 0
	AlarmMode_EMERGENCY_ALARM_WITH_CALL            AlarmMode = 1
	AlarmMode_EMERGENCY_ALARM_WITH_VOICE_TO_FOLLOW AlarmMode = 2
)

var AlarmMode_name = map[int32]string{
	0: "EMERGENCY_ALARM",
	1: "EMERGENCY_ALARM_WITH_CALL",
	2: "EMERGENCY_ALARM_WITH_VOICE_TO_FOLLOW",
}
var AlarmMode_value = map[string]int32{
	"EMERGENCY_ALARM":                      0,
	"EMERGENCY_ALARM_WITH_CALL":            1,
	"EMERGENCY_ALARM_WITH_VOICE_TO_FOLLOW": 2,
}

func (x AlarmMode) String() string {
	return proto.EnumName(AlarmMode_name, int32(x))
}
func (AlarmMode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

//
// ------------------
// Contacts
// ------------------
// https://github.com/yeyus/md380-webtools/wiki/MD389---Digital-Contact
type CallType int32

const (
	CallType_CALL_TYPE_NOT_SET CallType = 0
	CallType_GROUP_CALL        CallType = 1
	CallType_PRIVATE_CALL      CallType = 2
	CallType_ALL_CALL          CallType = 3
)

var CallType_name = map[int32]string{
	0: "CALL_TYPE_NOT_SET",
	1: "GROUP_CALL",
	2: "PRIVATE_CALL",
	3: "ALL_CALL",
}
var CallType_value = map[string]int32{
	"CALL_TYPE_NOT_SET": 0,
	"GROUP_CALL":        1,
	"PRIVATE_CALL":      2,
	"ALL_CALL":          3,
}

func (x CallType) String() string {
	return proto.EnumName(CallType_name, int32(x))
}
func (CallType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

//
// ------------------
// Codeplug
// ------------------
type TyteraCodeplug struct {
	BasicInformation  *BasicInformation  `protobuf:"bytes,1,opt,name=basic_information,json=basicInformation" json:"basic_information,omitempty"`
	GeneralSettings   *GeneralSettings   `protobuf:"bytes,2,opt,name=general_settings,json=generalSettings" json:"general_settings,omitempty"`
	MenuItems         *MenuItems         `protobuf:"bytes,3,opt,name=menu_items,json=menuItems" json:"menu_items,omitempty"`
	ButtonDefinitions *ButtonDefinitions `protobuf:"bytes,4,opt,name=button_definitions,json=buttonDefinitions" json:"button_definitions,omitempty"`
	MessagePresets    *MessagePresets    `protobuf:"bytes,5,opt,name=message_presets,json=messagePresets" json:"message_presets,omitempty"`
	PrivacySettings   *PrivacySettings   `protobuf:"bytes,6,opt,name=privacy_settings,json=privacySettings" json:"privacy_settings,omitempty"`
	EmergencySystems  *EmergencySystems  `protobuf:"bytes,7,opt,name=emergency_systems,json=emergencySystems" json:"emergency_systems,omitempty"`
	Contacts          *Contacts          `protobuf:"bytes,8,opt,name=contacts" json:"contacts,omitempty"`
}

func (m *TyteraCodeplug) Reset()                    { *m = TyteraCodeplug{} }
func (m *TyteraCodeplug) String() string            { return proto.CompactTextString(m) }
func (*TyteraCodeplug) ProtoMessage()               {}
func (*TyteraCodeplug) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TyteraCodeplug) GetBasicInformation() *BasicInformation {
	if m != nil {
		return m.BasicInformation
	}
	return nil
}

func (m *TyteraCodeplug) GetGeneralSettings() *GeneralSettings {
	if m != nil {
		return m.GeneralSettings
	}
	return nil
}

func (m *TyteraCodeplug) GetMenuItems() *MenuItems {
	if m != nil {
		return m.MenuItems
	}
	return nil
}

func (m *TyteraCodeplug) GetButtonDefinitions() *ButtonDefinitions {
	if m != nil {
		return m.ButtonDefinitions
	}
	return nil
}

func (m *TyteraCodeplug) GetMessagePresets() *MessagePresets {
	if m != nil {
		return m.MessagePresets
	}
	return nil
}

func (m *TyteraCodeplug) GetPrivacySettings() *PrivacySettings {
	if m != nil {
		return m.PrivacySettings
	}
	return nil
}

func (m *TyteraCodeplug) GetEmergencySystems() *EmergencySystems {
	if m != nil {
		return m.EmergencySystems
	}
	return nil
}

func (m *TyteraCodeplug) GetContacts() *Contacts {
	if m != nil {
		return m.Contacts
	}
	return nil
}

//
// ------------------
// Basic Information
// ------------------
// https://github.com/yeyus/md380-webtools/wiki/MD389---Basic-Information
type BasicInformation struct {
	ModelName       string                     `protobuf:"bytes,1,opt,name=model_name,json=modelName" json:"model_name,omitempty"`
	RadioBands      []RadioBand                `protobuf:"varint,2,rep,packed,name=radio_bands,json=radioBands,enum=go.ea7jmf.codeplug.tytera.RadioBand" json:"radio_bands,omitempty"`
	HardwareVersion string                     `protobuf:"bytes,3,opt,name=hardware_version,json=hardwareVersion" json:"hardware_version,omitempty"`
	McuVersion      string                     `protobuf:"bytes,4,opt,name=mcu_version,json=mcuVersion" json:"mcu_version,omitempty"`
	DeviceId        string                     `protobuf:"bytes,5,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	LastProgramDate *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=last_program_date,json=lastProgramDate" json:"last_program_date,omitempty"`
	CpsVersion      string                     `protobuf:"bytes,7,opt,name=cps_version,json=cpsVersion" json:"cps_version,omitempty"`
}

func (m *BasicInformation) Reset()                    { *m = BasicInformation{} }
func (m *BasicInformation) String() string            { return proto.CompactTextString(m) }
func (*BasicInformation) ProtoMessage()               {}
func (*BasicInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BasicInformation) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *BasicInformation) GetRadioBands() []RadioBand {
	if m != nil {
		return m.RadioBands
	}
	return nil
}

func (m *BasicInformation) GetHardwareVersion() string {
	if m != nil {
		return m.HardwareVersion
	}
	return ""
}

func (m *BasicInformation) GetMcuVersion() string {
	if m != nil {
		return m.McuVersion
	}
	return ""
}

func (m *BasicInformation) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *BasicInformation) GetLastProgramDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastProgramDate
	}
	return nil
}

func (m *BasicInformation) GetCpsVersion() string {
	if m != nil {
		return m.CpsVersion
	}
	return ""
}

type GeneralSettings struct {
	ScreenLines              []string        `protobuf:"bytes,1,rep,name=screen_lines,json=screenLines" json:"screen_lines,omitempty"`
	MonitorType              MonitorType     `protobuf:"varint,2,opt,name=monitor_type,json=monitorType,enum=go.ea7jmf.codeplug.tytera.MonitorType" json:"monitor_type,omitempty"`
	DisableLeds              bool            `protobuf:"varint,3,opt,name=disable_leds,json=disableLeds" json:"disable_leds,omitempty"`
	TalkPermitTone           SystemType      `protobuf:"varint,4,opt,name=talk_permit_tone,json=talkPermitTone,enum=go.ea7jmf.codeplug.tytera.SystemType" json:"talk_permit_tone,omitempty"`
	DisablePasswordAndLock   bool            `protobuf:"varint,5,opt,name=disable_password_and_lock,json=disablePasswordAndLock" json:"disable_password_and_lock,omitempty"`
	DisableChFreeTone        bool            `protobuf:"varint,6,opt,name=disable_ch_free_tone,json=disableChFreeTone" json:"disable_ch_free_tone,omitempty"`
	DisableTones             bool            `protobuf:"varint,7,opt,name=disable_tones,json=disableTones" json:"disable_tones,omitempty"`
	BatSaveReceiveMode       bool            `protobuf:"varint,8,opt,name=bat_save_receive_mode,json=batSaveReceiveMode" json:"bat_save_receive_mode,omitempty"`
	BatSavePreamble          bool            `protobuf:"varint,9,opt,name=bat_save_preamble,json=batSavePreamble" json:"bat_save_preamble,omitempty"`
	IntroScreenMode          IntroScreenMode `protobuf:"varint,10,opt,name=intro_screen_mode,json=introScreenMode,enum=go.ea7jmf.codeplug.tytera.IntroScreenMode" json:"intro_screen_mode,omitempty"`
	RadioId                  uint32          `protobuf:"varint,11,opt,name=radio_id,json=radioId" json:"radio_id,omitempty"`
	TxPreamble               uint32          `protobuf:"varint,12,opt,name=tx_preamble,json=txPreamble" json:"tx_preamble,omitempty"`
	GroupCallHang            uint32          `protobuf:"varint,13,opt,name=group_call_hang,json=groupCallHang" json:"group_call_hang,omitempty"`
	PrivateCallHang          uint32          `protobuf:"varint,14,opt,name=private_call_hang,json=privateCallHang" json:"private_call_hang,omitempty"`
	VoxSensitivity           uint32          `protobuf:"varint,15,opt,name=vox_sensitivity,json=voxSensitivity" json:"vox_sensitivity,omitempty"`
	RxLowBattery             uint32          `protobuf:"varint,16,opt,name=rx_low_battery,json=rxLowBattery" json:"rx_low_battery,omitempty"`
	CallAlertTone            uint32          `protobuf:"varint,17,opt,name=call_alert_tone,json=callAlertTone" json:"call_alert_tone,omitempty"`
	LoneWorkerResponse       uint32          `protobuf:"varint,18,opt,name=lone_worker_response,json=loneWorkerResponse" json:"lone_worker_response,omitempty"`
	LoneWorkerReminder       uint32          `protobuf:"varint,19,opt,name=lone_worker_reminder,json=loneWorkerReminder" json:"lone_worker_reminder,omitempty"`
	ScanDigitalHangTime      uint32          `protobuf:"varint,20,opt,name=scan_digital_hang_time,json=scanDigitalHangTime" json:"scan_digital_hang_time,omitempty"`
	ScanAnalogHangTime       uint32          `protobuf:"varint,21,opt,name=scan_analog_hang_time,json=scanAnalogHangTime" json:"scan_analog_hang_time,omitempty"`
	KeypadLock               uint32          `protobuf:"varint,22,opt,name=keypad_lock,json=keypadLock" json:"keypad_lock,omitempty"`
	OperationMode            OperationMode   `protobuf:"varint,23,opt,name=operation_mode,json=operationMode,enum=go.ea7jmf.codeplug.tytera.OperationMode" json:"operation_mode,omitempty"`
	PowerOnPassword          uint32          `protobuf:"varint,24,opt,name=power_on_password,json=powerOnPassword" json:"power_on_password,omitempty"`
	RadioProgrammingPassword uint32          `protobuf:"varint,25,opt,name=radio_programming_password,json=radioProgrammingPassword" json:"radio_programming_password,omitempty"`
	PcProgrammingPassword    string          `protobuf:"bytes,26,opt,name=pc_programming_password,json=pcProgrammingPassword" json:"pc_programming_password,omitempty"`
	RadioName                string          `protobuf:"bytes,27,opt,name=radio_name,json=radioName" json:"radio_name,omitempty"`
}

func (m *GeneralSettings) Reset()                    { *m = GeneralSettings{} }
func (m *GeneralSettings) String() string            { return proto.CompactTextString(m) }
func (*GeneralSettings) ProtoMessage()               {}
func (*GeneralSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GeneralSettings) GetScreenLines() []string {
	if m != nil {
		return m.ScreenLines
	}
	return nil
}

func (m *GeneralSettings) GetMonitorType() MonitorType {
	if m != nil {
		return m.MonitorType
	}
	return MonitorType_SILENT
}

func (m *GeneralSettings) GetDisableLeds() bool {
	if m != nil {
		return m.DisableLeds
	}
	return false
}

func (m *GeneralSettings) GetTalkPermitTone() SystemType {
	if m != nil {
		return m.TalkPermitTone
	}
	return SystemType_NONE
}

func (m *GeneralSettings) GetDisablePasswordAndLock() bool {
	if m != nil {
		return m.DisablePasswordAndLock
	}
	return false
}

func (m *GeneralSettings) GetDisableChFreeTone() bool {
	if m != nil {
		return m.DisableChFreeTone
	}
	return false
}

func (m *GeneralSettings) GetDisableTones() bool {
	if m != nil {
		return m.DisableTones
	}
	return false
}

func (m *GeneralSettings) GetBatSaveReceiveMode() bool {
	if m != nil {
		return m.BatSaveReceiveMode
	}
	return false
}

func (m *GeneralSettings) GetBatSavePreamble() bool {
	if m != nil {
		return m.BatSavePreamble
	}
	return false
}

func (m *GeneralSettings) GetIntroScreenMode() IntroScreenMode {
	if m != nil {
		return m.IntroScreenMode
	}
	return IntroScreenMode_CHAR_STRING
}

func (m *GeneralSettings) GetRadioId() uint32 {
	if m != nil {
		return m.RadioId
	}
	return 0
}

func (m *GeneralSettings) GetTxPreamble() uint32 {
	if m != nil {
		return m.TxPreamble
	}
	return 0
}

func (m *GeneralSettings) GetGroupCallHang() uint32 {
	if m != nil {
		return m.GroupCallHang
	}
	return 0
}

func (m *GeneralSettings) GetPrivateCallHang() uint32 {
	if m != nil {
		return m.PrivateCallHang
	}
	return 0
}

func (m *GeneralSettings) GetVoxSensitivity() uint32 {
	if m != nil {
		return m.VoxSensitivity
	}
	return 0
}

func (m *GeneralSettings) GetRxLowBattery() uint32 {
	if m != nil {
		return m.RxLowBattery
	}
	return 0
}

func (m *GeneralSettings) GetCallAlertTone() uint32 {
	if m != nil {
		return m.CallAlertTone
	}
	return 0
}

func (m *GeneralSettings) GetLoneWorkerResponse() uint32 {
	if m != nil {
		return m.LoneWorkerResponse
	}
	return 0
}

func (m *GeneralSettings) GetLoneWorkerReminder() uint32 {
	if m != nil {
		return m.LoneWorkerReminder
	}
	return 0
}

func (m *GeneralSettings) GetScanDigitalHangTime() uint32 {
	if m != nil {
		return m.ScanDigitalHangTime
	}
	return 0
}

func (m *GeneralSettings) GetScanAnalogHangTime() uint32 {
	if m != nil {
		return m.ScanAnalogHangTime
	}
	return 0
}

func (m *GeneralSettings) GetKeypadLock() uint32 {
	if m != nil {
		return m.KeypadLock
	}
	return 0
}

func (m *GeneralSettings) GetOperationMode() OperationMode {
	if m != nil {
		return m.OperationMode
	}
	return OperationMode_MR
}

func (m *GeneralSettings) GetPowerOnPassword() uint32 {
	if m != nil {
		return m.PowerOnPassword
	}
	return 0
}

func (m *GeneralSettings) GetRadioProgrammingPassword() uint32 {
	if m != nil {
		return m.RadioProgrammingPassword
	}
	return 0
}

func (m *GeneralSettings) GetPcProgrammingPassword() string {
	if m != nil {
		return m.PcProgrammingPassword
	}
	return ""
}

func (m *GeneralSettings) GetRadioName() string {
	if m != nil {
		return m.RadioName
	}
	return ""
}

type MenuItems struct {
	HangTime     uint32         `protobuf:"varint,1,opt,name=hang_time,json=hangTime" json:"hang_time,omitempty"`
	TextMessages bool           `protobuf:"varint,2,opt,name=text_messages,json=textMessages" json:"text_messages,omitempty"`
	Contacts     *ContactsMenu  `protobuf:"bytes,3,opt,name=contacts" json:"contacts,omitempty"`
	CallLog      *CallLogMenu   `protobuf:"bytes,4,opt,name=call_log,json=callLog" json:"call_log,omitempty"`
	Scan         *ScanMenu      `protobuf:"bytes,5,opt,name=scan" json:"scan,omitempty"`
	Utilities    *UtilitiesMenu `protobuf:"bytes,6,opt,name=utilities" json:"utilities,omitempty"`
}

func (m *MenuItems) Reset()                    { *m = MenuItems{} }
func (m *MenuItems) String() string            { return proto.CompactTextString(m) }
func (*MenuItems) ProtoMessage()               {}
func (*MenuItems) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MenuItems) GetHangTime() uint32 {
	if m != nil {
		return m.HangTime
	}
	return 0
}

func (m *MenuItems) GetTextMessages() bool {
	if m != nil {
		return m.TextMessages
	}
	return false
}

func (m *MenuItems) GetContacts() *ContactsMenu {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *MenuItems) GetCallLog() *CallLogMenu {
	if m != nil {
		return m.CallLog
	}
	return nil
}

func (m *MenuItems) GetScan() *ScanMenu {
	if m != nil {
		return m.Scan
	}
	return nil
}

func (m *MenuItems) GetUtilities() *UtilitiesMenu {
	if m != nil {
		return m.Utilities
	}
	return nil
}

type ContactsMenu struct {
	RadioDisable  bool `protobuf:"varint,1,opt,name=radio_disable,json=radioDisable" json:"radio_disable,omitempty"`
	RadioEnable   bool `protobuf:"varint,2,opt,name=radio_enable,json=radioEnable" json:"radio_enable,omitempty"`
	RemoteMonitor bool `protobuf:"varint,3,opt,name=remote_monitor,json=remoteMonitor" json:"remote_monitor,omitempty"`
	RadioCheck    bool `protobuf:"varint,4,opt,name=radio_check,json=radioCheck" json:"radio_check,omitempty"`
	ManualDial    bool `protobuf:"varint,5,opt,name=manual_dial,json=manualDial" json:"manual_dial,omitempty"`
	Edit          bool `protobuf:"varint,6,opt,name=edit" json:"edit,omitempty"`
	CallAlert     bool `protobuf:"varint,7,opt,name=call_alert,json=callAlert" json:"call_alert,omitempty"`
	ProgramKey    bool `protobuf:"varint,8,opt,name=program_key,json=programKey" json:"program_key,omitempty"`
}

func (m *ContactsMenu) Reset()                    { *m = ContactsMenu{} }
func (m *ContactsMenu) String() string            { return proto.CompactTextString(m) }
func (*ContactsMenu) ProtoMessage()               {}
func (*ContactsMenu) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ContactsMenu) GetRadioDisable() bool {
	if m != nil {
		return m.RadioDisable
	}
	return false
}

func (m *ContactsMenu) GetRadioEnable() bool {
	if m != nil {
		return m.RadioEnable
	}
	return false
}

func (m *ContactsMenu) GetRemoteMonitor() bool {
	if m != nil {
		return m.RemoteMonitor
	}
	return false
}

func (m *ContactsMenu) GetRadioCheck() bool {
	if m != nil {
		return m.RadioCheck
	}
	return false
}

func (m *ContactsMenu) GetManualDial() bool {
	if m != nil {
		return m.ManualDial
	}
	return false
}

func (m *ContactsMenu) GetEdit() bool {
	if m != nil {
		return m.Edit
	}
	return false
}

func (m *ContactsMenu) GetCallAlert() bool {
	if m != nil {
		return m.CallAlert
	}
	return false
}

func (m *ContactsMenu) GetProgramKey() bool {
	if m != nil {
		return m.ProgramKey
	}
	return false
}

type CallLogMenu struct {
	OutgoingRadio bool `protobuf:"varint,1,opt,name=outgoing_radio,json=outgoingRadio" json:"outgoing_radio,omitempty"`
	Answered      bool `protobuf:"varint,2,opt,name=answered" json:"answered,omitempty"`
	Missed        bool `protobuf:"varint,3,opt,name=missed" json:"missed,omitempty"`
}

func (m *CallLogMenu) Reset()                    { *m = CallLogMenu{} }
func (m *CallLogMenu) String() string            { return proto.CompactTextString(m) }
func (*CallLogMenu) ProtoMessage()               {}
func (*CallLogMenu) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CallLogMenu) GetOutgoingRadio() bool {
	if m != nil {
		return m.OutgoingRadio
	}
	return false
}

func (m *CallLogMenu) GetAnswered() bool {
	if m != nil {
		return m.Answered
	}
	return false
}

func (m *CallLogMenu) GetMissed() bool {
	if m != nil {
		return m.Missed
	}
	return false
}

type ScanMenu struct {
	EditList bool `protobuf:"varint,1,opt,name=edit_list,json=editList" json:"edit_list,omitempty"`
	Scan     bool `protobuf:"varint,2,opt,name=scan" json:"scan,omitempty"`
}

func (m *ScanMenu) Reset()                    { *m = ScanMenu{} }
func (m *ScanMenu) String() string            { return proto.CompactTextString(m) }
func (*ScanMenu) ProtoMessage()               {}
func (*ScanMenu) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ScanMenu) GetEditList() bool {
	if m != nil {
		return m.EditList
	}
	return false
}

func (m *ScanMenu) GetScan() bool {
	if m != nil {
		return m.Scan
	}
	return false
}

type UtilitiesMenu struct {
	ToneOrAlert     bool `protobuf:"varint,1,opt,name=tone_or_alert,json=toneOrAlert" json:"tone_or_alert,omitempty"`
	Talkaround      bool `protobuf:"varint,2,opt,name=talkaround" json:"talkaround,omitempty"`
	Vox             bool `protobuf:"varint,3,opt,name=vox" json:"vox,omitempty"`
	Squelch         bool `protobuf:"varint,4,opt,name=squelch" json:"squelch,omitempty"`
	LedIndicator    bool `protobuf:"varint,5,opt,name=led_indicator,json=ledIndicator" json:"led_indicator,omitempty"`
	KeyboardLock    bool `protobuf:"varint,6,opt,name=keyboard_lock,json=keyboardLock" json:"keyboard_lock,omitempty"`
	IntroScreen     bool `protobuf:"varint,7,opt,name=intro_screen,json=introScreen" json:"intro_screen,omitempty"`
	Backlight       bool `protobuf:"varint,8,opt,name=backlight" json:"backlight,omitempty"`
	Power           bool `protobuf:"varint,9,opt,name=power" json:"power,omitempty"`
	Gps             bool `protobuf:"varint,10,opt,name=gps" json:"gps,omitempty"`
	ProgramRadio    bool `protobuf:"varint,11,opt,name=program_radio,json=programRadio" json:"program_radio,omitempty"`
	DisplayMode     bool `protobuf:"varint,12,opt,name=display_mode,json=displayMode" json:"display_mode,omitempty"`
	PasswordAndLock bool `protobuf:"varint,13,opt,name=password_and_lock,json=passwordAndLock" json:"password_and_lock,omitempty"`
}

func (m *UtilitiesMenu) Reset()                    { *m = UtilitiesMenu{} }
func (m *UtilitiesMenu) String() string            { return proto.CompactTextString(m) }
func (*UtilitiesMenu) ProtoMessage()               {}
func (*UtilitiesMenu) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UtilitiesMenu) GetToneOrAlert() bool {
	if m != nil {
		return m.ToneOrAlert
	}
	return false
}

func (m *UtilitiesMenu) GetTalkaround() bool {
	if m != nil {
		return m.Talkaround
	}
	return false
}

func (m *UtilitiesMenu) GetVox() bool {
	if m != nil {
		return m.Vox
	}
	return false
}

func (m *UtilitiesMenu) GetSquelch() bool {
	if m != nil {
		return m.Squelch
	}
	return false
}

func (m *UtilitiesMenu) GetLedIndicator() bool {
	if m != nil {
		return m.LedIndicator
	}
	return false
}

func (m *UtilitiesMenu) GetKeyboardLock() bool {
	if m != nil {
		return m.KeyboardLock
	}
	return false
}

func (m *UtilitiesMenu) GetIntroScreen() bool {
	if m != nil {
		return m.IntroScreen
	}
	return false
}

func (m *UtilitiesMenu) GetBacklight() bool {
	if m != nil {
		return m.Backlight
	}
	return false
}

func (m *UtilitiesMenu) GetPower() bool {
	if m != nil {
		return m.Power
	}
	return false
}

func (m *UtilitiesMenu) GetGps() bool {
	if m != nil {
		return m.Gps
	}
	return false
}

func (m *UtilitiesMenu) GetProgramRadio() bool {
	if m != nil {
		return m.ProgramRadio
	}
	return false
}

func (m *UtilitiesMenu) GetDisplayMode() bool {
	if m != nil {
		return m.DisplayMode
	}
	return false
}

func (m *UtilitiesMenu) GetPasswordAndLock() bool {
	if m != nil {
		return m.PasswordAndLock
	}
	return false
}

type OneTouchAccessEntry struct {
	Mode     SystemType       `protobuf:"varint,1,opt,name=mode,enum=go.ea7jmf.codeplug.tytera.SystemType" json:"mode,omitempty"`
	CallType OneTouchCallType `protobuf:"varint,2,opt,name=call_type,json=callType,enum=go.ea7jmf.codeplug.tytera.OneTouchCallType" json:"call_type,omitempty"`
	// only if Mode = digital
	MessagePreset uint32 `protobuf:"varint,3,opt,name=message_preset,json=messagePreset" json:"message_preset,omitempty"`
	ContactIndex  uint32 `protobuf:"varint,4,opt,name=contact_index,json=contactIndex" json:"contact_index,omitempty"`
	// only if Mode = analog
	DtmfEncodePreset uint32 `protobuf:"varint,5,opt,name=dtmf_encode_preset,json=dtmfEncodePreset" json:"dtmf_encode_preset,omitempty"`
}

func (m *OneTouchAccessEntry) Reset()                    { *m = OneTouchAccessEntry{} }
func (m *OneTouchAccessEntry) String() string            { return proto.CompactTextString(m) }
func (*OneTouchAccessEntry) ProtoMessage()               {}
func (*OneTouchAccessEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *OneTouchAccessEntry) GetMode() SystemType {
	if m != nil {
		return m.Mode
	}
	return SystemType_NONE
}

func (m *OneTouchAccessEntry) GetCallType() OneTouchCallType {
	if m != nil {
		return m.CallType
	}
	return OneTouchCallType_NO_CALL_TYPE
}

func (m *OneTouchAccessEntry) GetMessagePreset() uint32 {
	if m != nil {
		return m.MessagePreset
	}
	return 0
}

func (m *OneTouchAccessEntry) GetContactIndex() uint32 {
	if m != nil {
		return m.ContactIndex
	}
	return 0
}

func (m *OneTouchAccessEntry) GetDtmfEncodePreset() uint32 {
	if m != nil {
		return m.DtmfEncodePreset
	}
	return 0
}

type ButtonDefinitions struct {
	LongPressDuration uint32         `protobuf:"varint,1,opt,name=long_press_duration,json=longPressDuration" json:"long_press_duration,omitempty"`
	SideShort_1       ButtonFunction `protobuf:"varint,2,opt,name=side_short_1,json=sideShort1,enum=go.ea7jmf.codeplug.tytera.ButtonFunction" json:"side_short_1,omitempty"`
	SideShort_2       ButtonFunction `protobuf:"varint,3,opt,name=side_short_2,json=sideShort2,enum=go.ea7jmf.codeplug.tytera.ButtonFunction" json:"side_short_2,omitempty"`
	SideLong_1        ButtonFunction `protobuf:"varint,4,opt,name=side_long_1,json=sideLong1,enum=go.ea7jmf.codeplug.tytera.ButtonFunction" json:"side_long_1,omitempty"`
	SideLong_2        ButtonFunction `protobuf:"varint,5,opt,name=side_long_2,json=sideLong2,enum=go.ea7jmf.codeplug.tytera.ButtonFunction" json:"side_long_2,omitempty"`
	// max of 6 entries
	OneTouchAccess []*OneTouchAccessEntry `protobuf:"bytes,6,rep,name=one_touch_access,json=oneTouchAccess" json:"one_touch_access,omitempty"`
	ContactKey_0   uint32                 `protobuf:"varint,100,opt,name=contact_key_0,json=contactKey0" json:"contact_key_0,omitempty"`
	ContactKey_1   uint32                 `protobuf:"varint,101,opt,name=contact_key_1,json=contactKey1" json:"contact_key_1,omitempty"`
	ContactKey_2   uint32                 `protobuf:"varint,102,opt,name=contact_key_2,json=contactKey2" json:"contact_key_2,omitempty"`
	ContactKey_3   uint32                 `protobuf:"varint,103,opt,name=contact_key_3,json=contactKey3" json:"contact_key_3,omitempty"`
	ContactKey_4   uint32                 `protobuf:"varint,104,opt,name=contact_key_4,json=contactKey4" json:"contact_key_4,omitempty"`
	ContactKey_5   uint32                 `protobuf:"varint,105,opt,name=contact_key_5,json=contactKey5" json:"contact_key_5,omitempty"`
	ContactKey_6   uint32                 `protobuf:"varint,106,opt,name=contact_key_6,json=contactKey6" json:"contact_key_6,omitempty"`
	ContactKey_7   uint32                 `protobuf:"varint,107,opt,name=contact_key_7,json=contactKey7" json:"contact_key_7,omitempty"`
	ContactKey_8   uint32                 `protobuf:"varint,108,opt,name=contact_key_8,json=contactKey8" json:"contact_key_8,omitempty"`
	ContactKey_9   uint32                 `protobuf:"varint,109,opt,name=contact_key_9,json=contactKey9" json:"contact_key_9,omitempty"`
}

func (m *ButtonDefinitions) Reset()                    { *m = ButtonDefinitions{} }
func (m *ButtonDefinitions) String() string            { return proto.CompactTextString(m) }
func (*ButtonDefinitions) ProtoMessage()               {}
func (*ButtonDefinitions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ButtonDefinitions) GetLongPressDuration() uint32 {
	if m != nil {
		return m.LongPressDuration
	}
	return 0
}

func (m *ButtonDefinitions) GetSideShort_1() ButtonFunction {
	if m != nil {
		return m.SideShort_1
	}
	return ButtonFunction_UNASSIGNED
}

func (m *ButtonDefinitions) GetSideShort_2() ButtonFunction {
	if m != nil {
		return m.SideShort_2
	}
	return ButtonFunction_UNASSIGNED
}

func (m *ButtonDefinitions) GetSideLong_1() ButtonFunction {
	if m != nil {
		return m.SideLong_1
	}
	return ButtonFunction_UNASSIGNED
}

func (m *ButtonDefinitions) GetSideLong_2() ButtonFunction {
	if m != nil {
		return m.SideLong_2
	}
	return ButtonFunction_UNASSIGNED
}

func (m *ButtonDefinitions) GetOneTouchAccess() []*OneTouchAccessEntry {
	if m != nil {
		return m.OneTouchAccess
	}
	return nil
}

func (m *ButtonDefinitions) GetContactKey_0() uint32 {
	if m != nil {
		return m.ContactKey_0
	}
	return 0
}

func (m *ButtonDefinitions) GetContactKey_1() uint32 {
	if m != nil {
		return m.ContactKey_1
	}
	return 0
}

func (m *ButtonDefinitions) GetContactKey_2() uint32 {
	if m != nil {
		return m.ContactKey_2
	}
	return 0
}

func (m *ButtonDefinitions) GetContactKey_3() uint32 {
	if m != nil {
		return m.ContactKey_3
	}
	return 0
}

func (m *ButtonDefinitions) GetContactKey_4() uint32 {
	if m != nil {
		return m.ContactKey_4
	}
	return 0
}

func (m *ButtonDefinitions) GetContactKey_5() uint32 {
	if m != nil {
		return m.ContactKey_5
	}
	return 0
}

func (m *ButtonDefinitions) GetContactKey_6() uint32 {
	if m != nil {
		return m.ContactKey_6
	}
	return 0
}

func (m *ButtonDefinitions) GetContactKey_7() uint32 {
	if m != nil {
		return m.ContactKey_7
	}
	return 0
}

func (m *ButtonDefinitions) GetContactKey_8() uint32 {
	if m != nil {
		return m.ContactKey_8
	}
	return 0
}

func (m *ButtonDefinitions) GetContactKey_9() uint32 {
	if m != nil {
		return m.ContactKey_9
	}
	return 0
}

//
// ------------------
// Message Presets
// ------------------
// https://github.com/yeyus/md380-webtools/wiki/MD389---Text-Messages
type MessagePresets struct {
	Messages []string `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
}

func (m *MessagePresets) Reset()                    { *m = MessagePresets{} }
func (m *MessagePresets) String() string            { return proto.CompactTextString(m) }
func (*MessagePresets) ProtoMessage()               {}
func (*MessagePresets) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MessagePresets) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

//
// ------------------
// Privacy Settings
// ------------------
// https://github.com/yeyus/md380-webtools/wiki/MD389---Privacy-Settings
type PrivacySettings struct {
	BasicKeys    [][]byte `protobuf:"bytes,1,rep,name=basic_keys,json=basicKeys,proto3" json:"basic_keys,omitempty"`
	EnhancedKeys [][]byte `protobuf:"bytes,2,rep,name=enhanced_keys,json=enhancedKeys,proto3" json:"enhanced_keys,omitempty"`
}

func (m *PrivacySettings) Reset()                    { *m = PrivacySettings{} }
func (m *PrivacySettings) String() string            { return proto.CompactTextString(m) }
func (*PrivacySettings) ProtoMessage()               {}
func (*PrivacySettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PrivacySettings) GetBasicKeys() [][]byte {
	if m != nil {
		return m.BasicKeys
	}
	return nil
}

func (m *PrivacySettings) GetEnhancedKeys() [][]byte {
	if m != nil {
		return m.EnhancedKeys
	}
	return nil
}

type EmergencySystemEntry struct {
	SystemName      string    `protobuf:"bytes,1,opt,name=system_name,json=systemName" json:"system_name,omitempty"`
	RevertChannel   uint32    `protobuf:"varint,2,opt,name=revert_channel,json=revertChannel" json:"revert_channel,omitempty"`
	AlarmType       AlarmType `protobuf:"varint,3,opt,name=alarm_type,json=alarmType,enum=go.ea7jmf.codeplug.tytera.AlarmType" json:"alarm_type,omitempty"`
	AlarmMode       AlarmMode `protobuf:"varint,4,opt,name=alarm_mode,json=alarmMode,enum=go.ea7jmf.codeplug.tytera.AlarmMode" json:"alarm_mode,omitempty"`
	ImpoliteRetries uint32    `protobuf:"varint,5,opt,name=impolite_retries,json=impoliteRetries" json:"impolite_retries,omitempty"`
	PoliteRetries   uint32    `protobuf:"varint,6,opt,name=polite_retries,json=politeRetries" json:"polite_retries,omitempty"`
	HotMicDuration  uint32    `protobuf:"varint,7,opt,name=hot_mic_duration,json=hotMicDuration" json:"hot_mic_duration,omitempty"`
}

func (m *EmergencySystemEntry) Reset()                    { *m = EmergencySystemEntry{} }
func (m *EmergencySystemEntry) String() string            { return proto.CompactTextString(m) }
func (*EmergencySystemEntry) ProtoMessage()               {}
func (*EmergencySystemEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *EmergencySystemEntry) GetSystemName() string {
	if m != nil {
		return m.SystemName
	}
	return ""
}

func (m *EmergencySystemEntry) GetRevertChannel() uint32 {
	if m != nil {
		return m.RevertChannel
	}
	return 0
}

func (m *EmergencySystemEntry) GetAlarmType() AlarmType {
	if m != nil {
		return m.AlarmType
	}
	return AlarmType_DISABLED_TYPE
}

func (m *EmergencySystemEntry) GetAlarmMode() AlarmMode {
	if m != nil {
		return m.AlarmMode
	}
	return AlarmMode_EMERGENCY_ALARM
}

func (m *EmergencySystemEntry) GetImpoliteRetries() uint32 {
	if m != nil {
		return m.ImpoliteRetries
	}
	return 0
}

func (m *EmergencySystemEntry) GetPoliteRetries() uint32 {
	if m != nil {
		return m.PoliteRetries
	}
	return 0
}

func (m *EmergencySystemEntry) GetHotMicDuration() uint32 {
	if m != nil {
		return m.HotMicDuration
	}
	return 0
}

type EmergencySystems struct {
	RadioDisableDecode           bool                    `protobuf:"varint,1,opt,name=radio_disable_decode,json=radioDisableDecode" json:"radio_disable_decode,omitempty"`
	RemoteMonitorDecode          bool                    `protobuf:"varint,2,opt,name=remote_monitor_decode,json=remoteMonitorDecode" json:"remote_monitor_decode,omitempty"`
	EmergencyRemoteMonitorDecode bool                    `protobuf:"varint,3,opt,name=emergency_remote_monitor_decode,json=emergencyRemoteMonitorDecode" json:"emergency_remote_monitor_decode,omitempty"`
	RemoteMonitorDuration        uint32                  `protobuf:"varint,4,opt,name=remote_monitor_duration,json=remoteMonitorDuration" json:"remote_monitor_duration,omitempty"`
	TxSyncWakeup                 uint32                  `protobuf:"varint,5,opt,name=tx_sync_wakeup,json=txSyncWakeup" json:"tx_sync_wakeup,omitempty"`
	TxWakeupMessageLimit         uint32                  `protobuf:"varint,6,opt,name=tx_wakeup_message_limit,json=txWakeupMessageLimit" json:"tx_wakeup_message_limit,omitempty"`
	Entries                      []*EmergencySystemEntry `protobuf:"bytes,7,rep,name=entries" json:"entries,omitempty"`
}

func (m *EmergencySystems) Reset()                    { *m = EmergencySystems{} }
func (m *EmergencySystems) String() string            { return proto.CompactTextString(m) }
func (*EmergencySystems) ProtoMessage()               {}
func (*EmergencySystems) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *EmergencySystems) GetRadioDisableDecode() bool {
	if m != nil {
		return m.RadioDisableDecode
	}
	return false
}

func (m *EmergencySystems) GetRemoteMonitorDecode() bool {
	if m != nil {
		return m.RemoteMonitorDecode
	}
	return false
}

func (m *EmergencySystems) GetEmergencyRemoteMonitorDecode() bool {
	if m != nil {
		return m.EmergencyRemoteMonitorDecode
	}
	return false
}

func (m *EmergencySystems) GetRemoteMonitorDuration() uint32 {
	if m != nil {
		return m.RemoteMonitorDuration
	}
	return 0
}

func (m *EmergencySystems) GetTxSyncWakeup() uint32 {
	if m != nil {
		return m.TxSyncWakeup
	}
	return 0
}

func (m *EmergencySystems) GetTxWakeupMessageLimit() uint32 {
	if m != nil {
		return m.TxWakeupMessageLimit
	}
	return 0
}

func (m *EmergencySystems) GetEntries() []*EmergencySystemEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type ContactEntry struct {
	Id              uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name            string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	CallReceiveTone bool     `protobuf:"varint,3,opt,name=call_receive_tone,json=callReceiveTone" json:"call_receive_tone,omitempty"`
	CallType        CallType `protobuf:"varint,4,opt,name=call_type,json=callType,enum=go.ea7jmf.codeplug.tytera.CallType" json:"call_type,omitempty"`
}

func (m *ContactEntry) Reset()                    { *m = ContactEntry{} }
func (m *ContactEntry) String() string            { return proto.CompactTextString(m) }
func (*ContactEntry) ProtoMessage()               {}
func (*ContactEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ContactEntry) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ContactEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContactEntry) GetCallReceiveTone() bool {
	if m != nil {
		return m.CallReceiveTone
	}
	return false
}

func (m *ContactEntry) GetCallType() CallType {
	if m != nil {
		return m.CallType
	}
	return CallType_CALL_TYPE_NOT_SET
}

type Contacts struct {
	Entries []*ContactEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *Contacts) Reset()                    { *m = Contacts{} }
func (m *Contacts) String() string            { return proto.CompactTextString(m) }
func (*Contacts) ProtoMessage()               {}
func (*Contacts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Contacts) GetEntries() []*ContactEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type RxGroupEntry struct {
	Name         string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ContactIndex []uint32 `protobuf:"varint,2,rep,packed,name=contact_index,json=contactIndex" json:"contact_index,omitempty"`
}

func (m *RxGroupEntry) Reset()                    { *m = RxGroupEntry{} }
func (m *RxGroupEntry) String() string            { return proto.CompactTextString(m) }
func (*RxGroupEntry) ProtoMessage()               {}
func (*RxGroupEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *RxGroupEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RxGroupEntry) GetContactIndex() []uint32 {
	if m != nil {
		return m.ContactIndex
	}
	return nil
}

type RxGroups struct {
	Entries []*RxGroupEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *RxGroups) Reset()                    { *m = RxGroups{} }
func (m *RxGroups) String() string            { return proto.CompactTextString(m) }
func (*RxGroups) ProtoMessage()               {}
func (*RxGroups) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *RxGroups) GetEntries() []*RxGroupEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*TyteraCodeplug)(nil), "go.ea7jmf.codeplug.tytera.TyteraCodeplug")
	proto.RegisterType((*BasicInformation)(nil), "go.ea7jmf.codeplug.tytera.BasicInformation")
	proto.RegisterType((*GeneralSettings)(nil), "go.ea7jmf.codeplug.tytera.GeneralSettings")
	proto.RegisterType((*MenuItems)(nil), "go.ea7jmf.codeplug.tytera.MenuItems")
	proto.RegisterType((*ContactsMenu)(nil), "go.ea7jmf.codeplug.tytera.ContactsMenu")
	proto.RegisterType((*CallLogMenu)(nil), "go.ea7jmf.codeplug.tytera.CallLogMenu")
	proto.RegisterType((*ScanMenu)(nil), "go.ea7jmf.codeplug.tytera.ScanMenu")
	proto.RegisterType((*UtilitiesMenu)(nil), "go.ea7jmf.codeplug.tytera.UtilitiesMenu")
	proto.RegisterType((*OneTouchAccessEntry)(nil), "go.ea7jmf.codeplug.tytera.OneTouchAccessEntry")
	proto.RegisterType((*ButtonDefinitions)(nil), "go.ea7jmf.codeplug.tytera.ButtonDefinitions")
	proto.RegisterType((*MessagePresets)(nil), "go.ea7jmf.codeplug.tytera.MessagePresets")
	proto.RegisterType((*PrivacySettings)(nil), "go.ea7jmf.codeplug.tytera.PrivacySettings")
	proto.RegisterType((*EmergencySystemEntry)(nil), "go.ea7jmf.codeplug.tytera.EmergencySystemEntry")
	proto.RegisterType((*EmergencySystems)(nil), "go.ea7jmf.codeplug.tytera.EmergencySystems")
	proto.RegisterType((*ContactEntry)(nil), "go.ea7jmf.codeplug.tytera.ContactEntry")
	proto.RegisterType((*Contacts)(nil), "go.ea7jmf.codeplug.tytera.Contacts")
	proto.RegisterType((*RxGroupEntry)(nil), "go.ea7jmf.codeplug.tytera.RxGroupEntry")
	proto.RegisterType((*RxGroups)(nil), "go.ea7jmf.codeplug.tytera.RxGroups")
	proto.RegisterEnum("go.ea7jmf.codeplug.tytera.RadioBand", RadioBand_name, RadioBand_value)
	proto.RegisterEnum("go.ea7jmf.codeplug.tytera.MonitorType", MonitorType_name, MonitorType_value)
	proto.RegisterEnum("go.ea7jmf.codeplug.tytera.SystemType", SystemType_name, SystemType_value)
	proto.RegisterEnum("go.ea7jmf.codeplug.tytera.IntroScreenMode", IntroScreenMode_name, IntroScreenMode_value)
	proto.RegisterEnum("go.ea7jmf.codeplug.tytera.OperationMode", OperationMode_name, OperationMode_value)
	proto.RegisterEnum("go.ea7jmf.codeplug.tytera.ButtonFunction", ButtonFunction_name, ButtonFunction_value)
	proto.RegisterEnum("go.ea7jmf.codeplug.tytera.OneTouchCallType", OneTouchCallType_name, OneTouchCallType_value)
	proto.RegisterEnum("go.ea7jmf.codeplug.tytera.AlarmType", AlarmType_name, AlarmType_value)
	proto.RegisterEnum("go.ea7jmf.codeplug.tytera.AlarmMode", AlarmMode_name, AlarmMode_value)
	proto.RegisterEnum("go.ea7jmf.codeplug.tytera.CallType", CallType_name, CallType_value)
}

func init() { proto.RegisterFile("proto/tytera/tytera.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 3046 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x59, 0x5d, 0x72, 0xdb, 0x48,
	0x92, 0x36, 0x29, 0x59, 0x22, 0x93, 0x7f, 0x50, 0xc9, 0xb2, 0x21, 0xf7, 0x8f, 0xdd, 0xb4, 0xdd,
	0x2d, 0xab, 0x3b, 0x64, 0xfd, 0xda, 0xed, 0xd8, 0x8d, 0xd8, 0x85, 0x49, 0x48, 0x62, 0x98, 0x22,
	0xd4, 0x20, 0x65, 0xbb, 0x7b, 0x63, 0xb7, 0x02, 0x02, 0x4a, 0x24, 0x5a, 0x20, 0xc0, 0x05, 0x40,
	0x49, 0x3c, 0xc7, 0xee, 0xfb, 0xee, 0xd3, 0x46, 0xec, 0x01, 0xe6, 0x00, 0xf3, 0x3a, 0x07, 0x98,
	0x13, 0xcc, 0xd3, 0x5c, 0x62, 0x26, 0xb2, 0xaa, 0xc0, 0x1f, 0x58, 0x43, 0xbb, 0xfb, 0x49, 0xc4,
	0x57, 0x5f, 0x66, 0x55, 0x65, 0x66, 0x65, 0x66, 0x95, 0x60, 0x7d, 0x10, 0x06, 0x71, 0xf0, 0x22,
	0x1e, 0xc5, 0x2c, 0xb4, 0xe4, 0x9f, 0x2d, 0x8e, 0x91, 0xf5, 0x6e, 0xb0, 0xc5, 0xac, 0x57, 0xbf,
	0xf6, 0x2f, 0xb6, 0xec, 0xc0, 0x61, 0x03, 0x6f, 0xd8, 0xdd, 0x12, 0x84, 0x87, 0x8f, 0xba, 0x41,
	0xd0, 0xf5, 0xd8, 0x0b, 0x4e, 0x3c, 0x1f, 0x5e, 0xbc, 0x88, 0xdd, 0x3e, 0x8b, 0x62, 0xab, 0x3f,
	0x10, 0xb2, 0xd5, 0xff, 0xbf, 0x0b, 0xe5, 0x0e, 0xe7, 0xd6, 0xa4, 0x28, 0xf9, 0x00, 0x2b, 0xe7,
	0x56, 0xe4, 0xda, 0xd4, 0xf5, 0x2f, 0x82, 0xb0, 0x6f, 0xc5, 0x6e, 0xe0, 0xab, 0x99, 0xc7, 0x99,
	0x8d, 0xc2, 0xee, 0xf7, 0x5b, 0xff, 0x70, 0xaa, 0xad, 0x37, 0x28, 0xd3, 0x98, 0x88, 0x98, 0xca,
	0x79, 0x0a, 0x21, 0x67, 0xa0, 0x74, 0x99, 0xcf, 0x42, 0xcb, 0xa3, 0x11, 0x8b, 0x63, 0xd7, 0xef,
	0x46, 0x6a, 0x96, 0x2b, 0xde, 0x9c, 0xa3, 0xf8, 0x48, 0x88, 0xb4, 0xa5, 0x84, 0x59, 0xe9, 0xce,
	0x02, 0xa4, 0x06, 0xd0, 0x67, 0xfe, 0x90, 0xba, 0x31, 0xeb, 0x47, 0xea, 0x02, 0x57, 0xf8, 0x74,
	0x8e, 0xc2, 0x13, 0xe6, 0x0f, 0x1b, 0xc8, 0x35, 0xf3, 0xfd, 0xe4, 0x27, 0xf9, 0x37, 0x20, 0xe7,
	0xc3, 0x38, 0x0e, 0x7c, 0xea, 0xb0, 0x0b, 0xd7, 0x77, 0x71, 0xc1, 0x91, 0xba, 0xc8, 0x95, 0xfd,
	0x30, 0x6f, 0xdb, 0x5c, 0xa8, 0x3e, 0x91, 0x31, 0x57, 0xce, 0xd3, 0x10, 0x31, 0xa1, 0xd2, 0x67,
	0x51, 0x64, 0x75, 0x19, 0x1d, 0x84, 0x2c, 0x62, 0x71, 0xa4, 0xde, 0xe5, 0x9a, 0x9f, 0xcf, 0x5d,
	0x26, 0x97, 0x38, 0x15, 0x02, 0x66, 0xb9, 0x3f, 0xf3, 0x8d, 0xc6, 0x1c, 0x84, 0xee, 0x95, 0x65,
	0x8f, 0x26, 0xc6, 0x5c, 0xfa, 0xa4, 0x31, 0x4f, 0x85, 0xc8, 0xc4, 0x98, 0x83, 0x59, 0x00, 0xbd,
	0xcf, 0xfa, 0x2c, 0xec, 0x32, 0x1f, 0x15, 0x8f, 0x22, 0x6e, 0xd3, 0xe5, 0x4f, 0x7a, 0x5f, 0x4f,
	0x64, 0xda, 0x42, 0xc4, 0x54, 0x58, 0x0a, 0x21, 0xff, 0x02, 0x39, 0x3b, 0xf0, 0x63, 0xcb, 0x8e,
	0x23, 0x35, 0xc7, 0x15, 0x3e, 0x99, 0xa3, 0xb0, 0x26, 0xa9, 0xe6, 0x58, 0xa8, 0xfa, 0xa7, 0x2c,
	0x28, 0xe9, 0x28, 0x23, 0x5f, 0x01, 0xf4, 0x03, 0x87, 0x79, 0xd4, 0xb7, 0xfa, 0x8c, 0x87, 0x69,
	0xde, 0xcc, 0x73, 0xa4, 0x65, 0xf5, 0x19, 0xd1, 0xa1, 0x10, 0x5a, 0x8e, 0x1b, 0xd0, 0x73, 0xcb,
	0x77, 0x30, 0xda, 0x16, 0x36, 0xca, 0x73, 0x83, 0xc3, 0x44, 0xf6, 0x1b, 0xcb, 0x77, 0x4c, 0x08,
	0x93, 0x9f, 0x11, 0x79, 0x0e, 0x4a, 0xcf, 0x0a, 0x9d, 0x6b, 0x2b, 0x64, 0xf4, 0x8a, 0x85, 0x11,
	0x1e, 0x89, 0x05, 0x3e, 0x57, 0x25, 0xc1, 0xdf, 0x09, 0x98, 0x3c, 0x82, 0x42, 0xdf, 0x1e, 0x8e,
	0x59, 0x8b, 0x9c, 0x05, 0x7d, 0x7b, 0x98, 0x10, 0xbe, 0x80, 0xbc, 0xc3, 0xae, 0x5c, 0x9b, 0x51,
	0xd7, 0xe1, 0x61, 0x90, 0x37, 0x73, 0x02, 0x68, 0x38, 0xe4, 0x10, 0x56, 0x3c, 0x2b, 0x8a, 0xe9,
	0x20, 0x0c, 0xba, 0xa1, 0xd5, 0xa7, 0x8e, 0x15, 0x33, 0xe9, 0xd6, 0x87, 0x5b, 0xe2, 0x30, 0x6f,
	0x25, 0x87, 0x79, 0xab, 0x93, 0x1c, 0x66, 0xb3, 0x82, 0x42, 0xa7, 0x42, 0xa6, 0x6e, 0xc5, 0x0c,
	0x57, 0x61, 0x0f, 0xa2, 0xf1, 0x2a, 0x96, 0xc5, 0x2a, 0xec, 0x41, 0x24, 0x57, 0x51, 0xfd, 0x23,
	0x40, 0x25, 0x75, 0xb2, 0xc8, 0x37, 0x50, 0x8c, 0xec, 0x90, 0x31, 0x9f, 0x7a, 0xae, 0xcf, 0x22,
	0x35, 0xf3, 0x78, 0x61, 0x23, 0x6f, 0x16, 0x04, 0xd6, 0x44, 0x88, 0x34, 0xa0, 0xd8, 0x0f, 0x7c,
	0x37, 0x0e, 0x42, 0x1a, 0x8f, 0x06, 0x8c, 0x1f, 0xdf, 0xf2, 0xee, 0xb7, 0xf3, 0xc2, 0x58, 0xd0,
	0x3b, 0xa3, 0x01, 0x33, 0x0b, 0xfd, 0xc9, 0x07, 0xce, 0xe6, 0xb8, 0x91, 0x75, 0xee, 0x31, 0xea,
	0x31, 0x47, 0x1c, 0xdc, 0x9c, 0x59, 0x90, 0x58, 0x93, 0x39, 0x11, 0x31, 0x40, 0x89, 0x2d, 0xef,
	0x92, 0x0e, 0x58, 0xd8, 0x77, 0x63, 0x1a, 0x07, 0x3e, 0xe3, 0x06, 0x2d, 0xef, 0x3e, 0x9b, 0x33,
	0xa3, 0x08, 0x38, 0x3e, 0x61, 0x19, 0xc5, 0x4f, 0xb9, 0x74, 0x27, 0xf0, 0x19, 0x79, 0x0d, 0xeb,
	0xc9, 0x9c, 0x03, 0x2b, 0x8a, 0xae, 0x83, 0xd0, 0xa1, 0x96, 0xef, 0x50, 0x2f, 0xb0, 0x2f, 0xb9,
	0x2f, 0x72, 0xe6, 0x7d, 0x49, 0x38, 0x95, 0xe3, 0x9a, 0xef, 0x34, 0x03, 0xfb, 0x92, 0xbc, 0x80,
	0x7b, 0x89, 0xa8, 0xdd, 0xa3, 0x17, 0x21, 0x63, 0x62, 0x3d, 0x4b, 0x5c, 0x6a, 0x45, 0x8e, 0xd5,
	0x7a, 0x87, 0x21, 0x63, 0x7c, 0xae, 0x27, 0x50, 0x4a, 0x04, 0x90, 0x28, 0x4e, 0x51, 0xce, 0x4c,
	0x36, 0x8d, 0x9c, 0x88, 0xec, 0xc0, 0xda, 0xb9, 0x15, 0xd3, 0xc8, 0xba, 0x62, 0x34, 0x64, 0x36,
	0x73, 0xaf, 0x18, 0xc5, 0xe8, 0xe5, 0x27, 0x24, 0x67, 0x92, 0x73, 0x2b, 0x6e, 0x5b, 0x57, 0xcc,
	0x14, 0x43, 0x27, 0x81, 0xc3, 0xc8, 0x26, 0xe6, 0x67, 0x29, 0x32, 0x08, 0x99, 0xd5, 0x3f, 0xf7,
	0x98, 0x9a, 0xe7, 0xf4, 0x8a, 0xa4, 0x9f, 0x4a, 0x98, 0xbc, 0x83, 0x15, 0xd7, 0x8f, 0xc3, 0x80,
	0x4a, 0xbf, 0x72, 0xd5, 0xc0, 0x2d, 0x38, 0x2f, 0x4b, 0x34, 0x50, 0xa6, 0xcd, 0x45, 0x70, 0x4a,
	0xb3, 0xe2, 0xce, 0x02, 0x64, 0x1d, 0x72, 0xe2, 0x58, 0xb9, 0x8e, 0x5a, 0x78, 0x9c, 0xd9, 0x28,
	0x99, 0xcb, 0xfc, 0xbb, 0xe1, 0x60, 0xe4, 0xc5, 0x37, 0x93, 0x85, 0x15, 0xf9, 0x28, 0xc4, 0x37,
	0xe3, 0x35, 0x7d, 0x0b, 0x95, 0x6e, 0x18, 0x0c, 0x07, 0xd4, 0xb6, 0x3c, 0x8f, 0xf6, 0x2c, 0xbf,
	0xab, 0x96, 0x38, 0xa9, 0xc4, 0xe1, 0x9a, 0xe5, 0x79, 0xc7, 0x96, 0xdf, 0xc5, 0x7d, 0xf2, 0xe4,
	0x14, 0xb3, 0x29, 0x66, 0x99, 0x33, 0x2b, 0x72, 0x60, 0xcc, 0xfd, 0x0e, 0x2a, 0x57, 0xc1, 0x0d,
	0x8d, 0x98, 0x1f, 0xb9, 0xb1, 0x7b, 0xe5, 0xc6, 0x23, 0xb5, 0xc2, 0x99, 0xe5, 0xab, 0xe0, 0xa6,
	0x3d, 0x41, 0xc9, 0x53, 0x28, 0x87, 0x37, 0xd4, 0x0b, 0xae, 0xe9, 0xb9, 0x15, 0xc7, 0x2c, 0x1c,
	0xa9, 0x0a, 0xe7, 0x15, 0xc3, 0x9b, 0x66, 0x70, 0xfd, 0x46, 0x60, 0xb8, 0x44, 0x3e, 0xa5, 0xe5,
	0xb1, 0x50, 0x86, 0xdd, 0x8a, 0x58, 0x22, 0xc2, 0x1a, 0xa2, 0xdc, 0xc5, 0xdb, 0x70, 0xcf, 0x0b,
	0x7c, 0x46, 0xaf, 0x83, 0xf0, 0x92, 0x85, 0x34, 0x64, 0xd1, 0x20, 0xf0, 0x23, 0xa6, 0x12, 0x4e,
	0x26, 0x38, 0xf6, 0x9e, 0x0f, 0x99, 0x72, 0xe4, 0x63, 0x89, 0xbe, 0xeb, 0x3b, 0x2c, 0x54, 0x57,
	0x3f, 0x96, 0x10, 0x23, 0x64, 0x0f, 0xee, 0x47, 0xb6, 0xe5, 0x53, 0xc7, 0xed, 0xba, 0xb1, 0x25,
	0xcc, 0x40, 0xb1, 0x8c, 0xab, 0xf7, 0xb8, 0xcc, 0x2a, 0x8e, 0xd6, 0xc5, 0x20, 0xda, 0x02, 0x93,
	0x02, 0x86, 0x15, 0x17, 0xb2, 0x7c, 0xcb, 0x0b, 0xba, 0x53, 0x32, 0x6b, 0x62, 0x1e, 0x1c, 0xd4,
	0xf8, 0xd8, 0x58, 0xe4, 0x11, 0x14, 0x2e, 0xd9, 0x68, 0x60, 0xc9, 0xc3, 0x70, 0x5f, 0xf8, 0x4d,
	0x40, 0xfc, 0x00, 0x18, 0x50, 0x0e, 0x06, 0x2c, 0xe4, 0x69, 0x57, 0x04, 0xd2, 0x03, 0x1e, 0x48,
	0x1b, 0x73, 0x02, 0xc9, 0x48, 0x04, 0x78, 0x18, 0x95, 0x82, 0xe9, 0x4f, 0xee, 0xe0, 0xe0, 0x9a,
	0x85, 0x34, 0xf0, 0xc7, 0xa7, 0x51, 0x55, 0xa5, 0x83, 0x71, 0xc0, 0xf0, 0x93, 0x43, 0x48, 0xfe,
	0x19, 0x1e, 0x8a, 0x80, 0x93, 0x89, 0xb1, 0xef, 0xfa, 0xdd, 0x89, 0xd0, 0x3a, 0x17, 0x52, 0x39,
	0xe3, 0x74, 0x42, 0x18, 0x4b, 0xbf, 0x84, 0x07, 0x03, 0xfb, 0x76, 0xd1, 0x87, 0x3c, 0x33, 0xae,
	0x0d, 0xec, 0xdb, 0xe4, 0xbe, 0x02, 0x51, 0x04, 0x44, 0x71, 0xf9, 0x42, 0x14, 0x17, 0x8e, 0x60,
	0x71, 0xa9, 0xfe, 0x39, 0x0b, 0xf9, 0x71, 0x33, 0x81, 0x79, 0x7d, 0x62, 0xe7, 0x0c, 0x5f, 0x51,
	0xae, 0x97, 0x58, 0xf7, 0x09, 0x94, 0x62, 0x76, 0x13, 0x53, 0x59, 0xc4, 0x45, 0xdf, 0x93, 0x33,
	0x8b, 0x08, 0xca, 0x42, 0x8f, 0x8d, 0xcc, 0xa4, 0x42, 0x8a, 0x36, 0xe6, 0xbb, 0xcf, 0xa8, 0x90,
	0xb8, 0x82, 0x49, 0x95, 0x24, 0x1a, 0xe4, 0x78, 0xec, 0x7a, 0x41, 0x57, 0xb6, 0x2f, 0xf3, 0xb2,
	0x33, 0x9e, 0xa0, 0x66, 0xd0, 0xe5, 0x3a, 0x96, 0x6d, 0xf1, 0x41, 0x5e, 0xc1, 0x22, 0x06, 0x88,
	0xec, 0x51, 0xe6, 0x55, 0xe9, 0xb6, 0x6d, 0xf9, 0x5c, 0x96, 0x0b, 0x90, 0x43, 0xc8, 0x0f, 0x63,
	0xd7, 0x73, 0x63, 0x97, 0x25, 0xcd, 0xc8, 0xbc, 0xe8, 0x38, 0x4b, 0xb8, 0x5c, 0xc5, 0x44, 0xb4,
	0xfa, 0x5f, 0x59, 0x28, 0x4e, 0x6f, 0x0f, 0xcd, 0x27, 0x1c, 0x21, 0x93, 0x27, 0xb7, 0x6f, 0xce,
	0x2c, 0x72, 0xb0, 0x2e, 0x30, 0x2c, 0x28, 0x82, 0xc4, 0x7c, 0xce, 0x11, 0x26, 0x16, 0xf5, 0x5f,
	0xe7, 0x10, 0x79, 0x06, 0xe5, 0x90, 0xf5, 0x83, 0x18, 0x93, 0x2c, 0xaf, 0x44, 0xb2, 0xea, 0x94,
	0x04, 0x2a, 0x6b, 0x15, 0x9e, 0x05, 0xa1, 0xc9, 0xee, 0x31, 0xfb, 0x92, 0x9b, 0x31, 0x27, 0xfb,
	0x81, 0x1a, 0x22, 0xbc, 0xc8, 0x5b, 0xfe, 0xd0, 0xf2, 0xa8, 0xe3, 0x5a, 0x9e, 0xac, 0x1c, 0x20,
	0xa0, 0xba, 0x6b, 0x79, 0x84, 0xc0, 0x22, 0x73, 0xdc, 0x58, 0x56, 0x07, 0xfe, 0x1b, 0xa3, 0x69,
	0x92, 0x55, 0x64, 0x35, 0xc8, 0x8f, 0x13, 0x0a, 0xea, 0x4c, 0xaa, 0xfe, 0x25, 0x1b, 0xc9, 0x02,
	0x00, 0x12, 0x7a, 0xcb, 0x46, 0xd5, 0x1e, 0x14, 0xa6, 0xdc, 0x85, 0x7b, 0x09, 0x86, 0x71, 0x37,
	0xc0, 0x70, 0xe6, 0x4b, 0x93, 0x46, 0x29, 0x25, 0x28, 0x6f, 0x65, 0xc8, 0x43, 0xc8, 0x59, 0x7e,
	0x74, 0xcd, 0x42, 0xe6, 0x48, 0x8b, 0x8c, 0xbf, 0xc9, 0x7d, 0x58, 0xea, 0xbb, 0x51, 0xc4, 0x1c,
	0x69, 0x06, 0xf9, 0x55, 0xfd, 0x27, 0xc8, 0x25, 0x9e, 0xc5, 0xb0, 0xc6, 0xd5, 0x53, 0xcf, 0x8d,
	0x62, 0x39, 0x43, 0x0e, 0x81, 0xa6, 0x1b, 0xc5, 0xb8, 0x4d, 0x1e, 0x29, 0x42, 0x31, 0xff, 0x5d,
	0xfd, 0xbf, 0x05, 0x28, 0xcd, 0x78, 0x96, 0x54, 0xa1, 0x84, 0x39, 0x94, 0x06, 0xa1, 0xdc, 0xbb,
	0x50, 0x53, 0x40, 0xd0, 0x08, 0xc5, 0xee, 0xbf, 0x06, 0xc0, 0x5a, 0x6d, 0x85, 0xc1, 0xd0, 0x4f,
	0x16, 0x3a, 0x85, 0x10, 0x05, 0x16, 0xae, 0x82, 0x1b, 0xb9, 0x4e, 0xfc, 0x49, 0x54, 0x58, 0x8e,
	0xfe, 0x73, 0xc8, 0x3c, 0xbb, 0x27, 0x1d, 0x94, 0x7c, 0x62, 0xb4, 0x78, 0xcc, 0xa1, 0xae, 0xef,
	0xb8, 0xb6, 0x85, 0x4e, 0x16, 0xfe, 0x29, 0x7a, 0xcc, 0x69, 0x24, 0x18, 0x92, 0x2e, 0xd9, 0xe8,
	0x3c, 0xb0, 0x42, 0x99, 0xf1, 0x84, 0xab, 0x8a, 0x09, 0xc8, 0x73, 0xde, 0x37, 0x50, 0x9c, 0xae,
	0x9f, 0xd2, 0x69, 0x85, 0xa9, 0x72, 0x48, 0xbe, 0x84, 0xfc, 0xb9, 0x65, 0x5f, 0x7a, 0x6e, 0xb7,
	0x17, 0x4b, 0xa7, 0x4d, 0x00, 0x72, 0x0f, 0xee, 0xf2, 0x54, 0x26, 0x0b, 0xb4, 0xf8, 0xc0, 0xcd,
	0x74, 0x07, 0x11, 0x2f, 0xc4, 0x39, 0x13, 0x7f, 0xe2, 0x6a, 0x12, 0xe7, 0x0b, 0x5f, 0x16, 0xc4,
	0x6a, 0x24, 0x28, 0x5c, 0x29, 0x3a, 0xa6, 0x81, 0x67, 0x8d, 0x44, 0xfe, 0x2d, 0x8e, 0x3b, 0x26,
	0xc4, 0xc6, 0x39, 0xf5, 0xa3, 0xc6, 0xa6, 0x24, 0x9a, 0x83, 0xc1, 0x6c, 0x47, 0x53, 0xfd, 0xef,
	0x2c, 0xac, 0x1a, 0x3e, 0xeb, 0x04, 0x43, 0xbb, 0xa7, 0xd9, 0x36, 0x8b, 0x22, 0xdd, 0x8f, 0xc3,
	0x11, 0x79, 0x0d, 0x8b, 0x5c, 0x7d, 0xe6, 0xb7, 0x74, 0x5a, 0x5c, 0x84, 0x1c, 0x03, 0x0f, 0xe8,
	0xe9, 0xde, 0x70, 0xde, 0xad, 0x21, 0x99, 0x1d, 0xc3, 0x9a, 0x6b, 0xe1, 0xa9, 0x8b, 0x77, 0x87,
	0xcf, 0xa0, 0x3c, 0x7b, 0x65, 0xe2, 0xae, 0x2f, 0x99, 0xa5, 0x99, 0x6b, 0x10, 0xda, 0x4d, 0x66,
	0x3e, 0x74, 0x37, 0xbb, 0xe1, 0xa1, 0x50, 0x32, 0x8b, 0x12, 0x6c, 0x20, 0x46, 0x7e, 0x00, 0xe2,
	0xc4, 0xfd, 0x0b, 0xca, 0x7c, 0x5c, 0x40, 0xa2, 0xef, 0x2e, 0x67, 0x2a, 0x38, 0xa2, 0xf3, 0x01,
	0xa1, 0xb2, 0xfa, 0x87, 0x25, 0x58, 0xf9, 0xe8, 0x56, 0x47, 0xb6, 0x60, 0xd5, 0x0b, 0xb0, 0x70,
	0x84, 0x2c, 0x8a, 0xa8, 0x33, 0x0c, 0x27, 0xf7, 0xe2, 0x92, 0xb9, 0x82, 0x43, 0x28, 0x1e, 0xd5,
	0xe5, 0x00, 0x79, 0x0b, 0xc5, 0xc8, 0x75, 0x18, 0x8d, 0x7a, 0x41, 0x18, 0xd3, 0x1d, 0x69, 0x8c,
	0xe7, 0x9f, 0xbc, 0x49, 0x1e, 0x0e, 0x7d, 0x9b, 0x5f, 0x9f, 0x01, 0xc5, 0xdb, 0x28, 0xbd, 0x93,
	0x52, 0xb6, 0xcb, 0x4d, 0xf1, 0x3b, 0x95, 0xed, 0x92, 0x06, 0x14, 0xb8, 0x32, 0xbe, 0x9d, 0x1d,
	0xd9, 0x4f, 0xff, 0x06, 0x5d, 0x79, 0x94, 0x6e, 0x06, 0x7e, 0x77, 0x67, 0x56, 0xd5, 0x2e, 0xb7,
	0xe8, 0xef, 0x53, 0xb5, 0x4b, 0x3e, 0x80, 0x82, 0x29, 0x22, 0xc6, 0x70, 0xa0, 0x16, 0x8f, 0x46,
	0x75, 0xe9, 0xf1, 0xc2, 0x46, 0x61, 0x77, 0xeb, 0x33, 0x02, 0x68, 0x2a, 0x7c, 0xcd, 0x72, 0x30,
	0x03, 0x62, 0xf6, 0x49, 0x42, 0xe4, 0x92, 0x8d, 0xe8, 0xb6, 0xea, 0x70, 0x9f, 0x15, 0x24, 0xf8,
	0x96, 0x8d, 0xb6, 0xd3, 0x9c, 0x1d, 0x95, 0xa5, 0x39, 0x3b, 0x69, 0xce, 0xae, 0x7a, 0x91, 0xe6,
	0xec, 0xa6, 0x39, 0x7b, 0x6a, 0x37, 0xcd, 0xd9, 0x4b, 0x73, 0xf6, 0xd5, 0x5e, 0x9a, 0xb3, 0x9f,
	0xe6, 0x1c, 0xa8, 0x6e, 0x9a, 0x73, 0x90, 0xe6, 0xbc, 0x54, 0x7f, 0x4d, 0x73, 0x5e, 0xa6, 0x39,
	0xaf, 0xd4, 0xcb, 0x34, 0xe7, 0x55, 0x9a, 0xf3, 0xa3, 0xea, 0xa5, 0x39, 0x3f, 0xa6, 0x39, 0xaf,
	0xd5, 0x7e, 0x9a, 0xf3, 0xba, 0xfa, 0x03, 0x94, 0x67, 0x9f, 0x2c, 0xb0, 0xf4, 0x8c, 0xfb, 0x1d,
	0x71, 0x97, 0x1c, 0x7f, 0x57, 0xcf, 0xa0, 0x92, 0x7a, 0x8b, 0xc0, 0xfa, 0x28, 0x1e, 0x9e, 0x2e,
	0xd9, 0x48, 0x08, 0x14, 0x31, 0x95, 0x46, 0xae, 0xfd, 0x96, 0x8d, 0x78, 0x8a, 0x64, 0x7e, 0xcf,
	0xf2, 0x6d, 0xe6, 0x08, 0x46, 0x96, 0x33, 0x8a, 0x09, 0x88, 0xa4, 0xea, 0x5f, 0xb2, 0x70, 0x2f,
	0xf5, 0x16, 0x21, 0x92, 0xda, 0x23, 0x28, 0x88, 0xd7, 0x8c, 0xe9, 0x87, 0x02, 0x10, 0x10, 0x7f,
	0x29, 0xe0, 0xad, 0xc1, 0x15, 0xf6, 0xfb, 0x76, 0xcf, 0xf2, 0x7d, 0xe6, 0xf1, 0x23, 0x5b, 0xc2,
	0xd6, 0x00, 0xd1, 0x9a, 0x00, 0x49, 0x0d, 0xc0, 0xf2, 0xac, 0xb0, 0x2f, 0x52, 0x9c, 0x38, 0x88,
	0xf3, 0xde, 0x13, 0x34, 0x24, 0xf3, 0xdc, 0x96, 0xb7, 0x92, 0x9f, 0x13, 0x25, 0x3c, 0xcf, 0x2e,
	0x7e, 0x9e, 0x12, 0xde, 0x42, 0x0b, 0x25, 0x3c, 0xd5, 0x3f, 0x07, 0xc5, 0xed, 0x0f, 0x02, 0xcf,
	0x8d, 0xf1, 0xea, 0x18, 0x87, 0xd8, 0x73, 0x89, 0x9c, 0x56, 0x49, 0x70, 0x53, 0xc0, 0xb8, 0xb7,
	0x14, 0x71, 0x49, 0xec, 0x6d, 0x96, 0xb6, 0x01, 0x4a, 0x2f, 0x88, 0x69, 0xdf, 0xb5, 0x27, 0x09,
	0x6e, 0x59, 0x5c, 0xa3, 0x7a, 0x41, 0x7c, 0xe2, 0xda, 0x49, 0x76, 0xab, 0xfe, 0xcf, 0x02, 0x28,
	0xe9, 0x27, 0x1f, 0xbc, 0xdb, 0xcc, 0x34, 0x69, 0xd4, 0x61, 0x76, 0x52, 0x47, 0x72, 0x26, 0x99,
	0xee, 0xd5, 0xea, 0x7c, 0x84, 0xec, 0xc2, 0xda, 0x6c, 0x3b, 0x96, 0x88, 0x88, 0xfa, 0xbf, 0x3a,
	0xd3, 0x95, 0x49, 0x19, 0x1d, 0x1e, 0x4d, 0x1e, 0xa8, 0x6e, 0x97, 0x16, 0x4d, 0xc2, 0x97, 0x63,
	0x9a, 0x79, 0x8b, 0x9a, 0x97, 0xf0, 0x20, 0x2d, 0x9c, 0x6c, 0x59, 0x94, 0x90, 0xb5, 0xd9, 0xc9,
	0x93, 0xbc, 0xfe, 0x14, 0xca, 0xf1, 0x0d, 0x8d, 0x46, 0xbe, 0x4d, 0xaf, 0xad, 0x4b, 0x36, 0x1c,
	0x48, 0x9b, 0x17, 0xe3, 0x9b, 0xf6, 0xc8, 0xb7, 0xdf, 0x73, 0x8c, 0x1c, 0xc0, 0x83, 0xf8, 0x46,
	0x12, 0x92, 0x9e, 0x9f, 0x7a, 0x6e, 0x5f, 0x76, 0x84, 0x25, 0xf3, 0x5e, 0x7c, 0x23, 0xa8, 0xf2,
	0xc8, 0x34, 0x71, 0x8c, 0x34, 0x60, 0x99, 0xf9, 0xc2, 0x41, 0xcb, 0x3c, 0xf7, 0xbd, 0xf8, 0xfc,
	0x27, 0x37, 0x91, 0xfc, 0x12, 0xf9, 0xea, 0xff, 0x66, 0xc6, 0x2d, 0xb4, 0x38, 0x00, 0x65, 0xc8,
	0xba, 0x8e, 0xac, 0x57, 0x59, 0xd7, 0xc1, 0xd6, 0x8d, 0x9f, 0x84, 0x2c, 0x3f, 0x09, 0xfc, 0x37,
	0x76, 0x0f, 0xbc, 0x7c, 0x27, 0x2f, 0x11, 0xfc, 0xe6, 0x2b, 0xac, 0xc9, 0x2f, 0xc4, 0xf2, 0x19,
	0x82, 0xdf, 0x7d, 0xff, 0x75, 0xba, 0xd4, 0x8b, 0x10, 0x7e, 0xf2, 0x89, 0x8b, 0xc6, 0x6c, 0x89,
	0xaf, 0x9e, 0x40, 0xae, 0x36, 0xb9, 0xb5, 0x8c, 0x77, 0x9e, 0xe1, 0x3b, 0xff, 0x8c, 0x9b, 0x4f,
	0x6a, 0xc7, 0x47, 0x50, 0x34, 0x6f, 0x8e, 0xc2, 0x60, 0x38, 0x10, 0x1b, 0x4e, 0x36, 0x98, 0x99,
	0xda, 0xe0, 0x47, 0xed, 0x02, 0xe6, 0x90, 0x54, 0xbb, 0x80, 0xeb, 0x92, 0x8a, 0x7e, 0xe3, 0xba,
	0xa6, 0xa7, 0x1f, 0xaf, 0x6b, 0xf3, 0x3f, 0x20, 0x3f, 0x7e, 0x54, 0x24, 0x15, 0x28, 0xbc, 0x3b,
	0x3e, 0xa4, 0x3b, 0x7b, 0x2f, 0xe9, 0xce, 0xab, 0x7d, 0xe5, 0x0e, 0x02, 0x67, 0xc7, 0x87, 0x74,
	0xef, 0x60, 0x9b, 0xee, 0x6f, 0x6f, 0x2b, 0x99, 0x04, 0xd8, 0xdf, 0xde, 0xa6, 0xfb, 0x3f, 0x6e,
	0x2b, 0xd9, 0x31, 0x70, 0xb0, 0x4d, 0x0f, 0x76, 0xb7, 0x95, 0x05, 0x52, 0x82, 0x5c, 0xbd, 0xd1,
	0xd6, 0xde, 0x34, 0xf5, 0xba, 0xf2, 0xb7, 0xcc, 0xe6, 0xf7, 0x50, 0x98, 0x7a, 0x63, 0x23, 0x00,
	0x4b, 0xed, 0x46, 0x53, 0x6f, 0x75, 0x94, 0x3b, 0x44, 0x81, 0xa2, 0x71, 0xaa, 0xb7, 0x68, 0xfb,
	0xa7, 0x33, 0xbd, 0x59, 0x3b, 0x56, 0x32, 0x9b, 0xaf, 0x01, 0x26, 0x4d, 0x1b, 0xc9, 0xc1, 0x62,
	0xcb, 0x68, 0xe9, 0xca, 0x1d, 0x52, 0x80, 0xe5, 0x7a, 0xe3, 0xa8, 0xd1, 0xd1, 0x9a, 0x4a, 0x06,
	0x55, 0x68, 0x2d, 0xad, 0x69, 0x1c, 0x29, 0x59, 0xa4, 0xbc, 0x31, 0x3a, 0xc7, 0xca, 0xc2, 0xe6,
	0x0b, 0xa8, 0xa4, 0xde, 0x85, 0x70, 0x69, 0xb5, 0x63, 0xcd, 0xa4, 0xed, 0x8e, 0xd9, 0x68, 0x1d,
	0x09, 0x35, 0xa7, 0x8d, 0x5a, 0xe7, 0xcc, 0xd4, 0x95, 0xcc, 0xe6, 0x33, 0x28, 0xcd, 0xdc, 0xff,
	0xc9, 0x12, 0x64, 0x4f, 0x4c, 0xe5, 0x0e, 0x29, 0xc2, 0x72, 0xed, 0x58, 0x6b, 0xb5, 0xf4, 0x26,
	0xae, 0xff, 0xaf, 0x0b, 0x50, 0x9e, 0xed, 0x0b, 0x48, 0x19, 0xe0, 0xac, 0xa5, 0xb5, 0xdb, 0x8d,
	0xa3, 0x96, 0x5e, 0x57, 0xee, 0x90, 0x75, 0x58, 0xd3, 0x9a, 0x4d, 0xaa, 0x35, 0x75, 0xb3, 0x43,
	0x3b, 0x46, 0x4b, 0x6f, 0x53, 0xa3, 0x65, 0x1c, 0x1e, 0x2a, 0x19, 0xdc, 0xa2, 0x7e, 0xa2, 0x9b,
	0x47, 0x7a, 0xab, 0xf6, 0x33, 0x35, 0x5a, 0x4a, 0x96, 0xac, 0x40, 0x69, 0x0a, 0x39, 0x3c, 0x54,
	0x16, 0x08, 0x81, 0xf2, 0x71, 0xe3, 0xe8, 0x98, 0x36, 0x8d, 0xf7, 0xf4, 0xd4, 0x78, 0xaf, 0x9b,
	0xca, 0x22, 0x2e, 0xf5, 0xc4, 0x68, 0x35, 0x3a, 0x86, 0xa9, 0xdc, 0x25, 0xab, 0x50, 0x69, 0x9d,
	0x35, 0xda, 0x5a, 0xab, 0xa6, 0xd3, 0xba, 0xde, 0xd4, 0x3b, 0xba, 0xb2, 0x44, 0xee, 0x03, 0x31,
	0x5a, 0x3a, 0xed, 0x18, 0x67, 0xb5, 0x63, 0xaa, 0xd5, 0x6a, 0x7a, 0xbb, 0x4d, 0x77, 0x94, 0xe5,
	0x5b, 0xf1, 0x5d, 0x25, 0x77, 0x2b, 0xbe, 0xa7, 0xe4, 0x6f, 0xc5, 0xf7, 0x15, 0xb8, 0x15, 0x3f,
	0x50, 0x0a, 0xb7, 0xe2, 0x2f, 0x95, 0x22, 0x79, 0x00, 0xab, 0xa6, 0x7e, 0xaa, 0x6b, 0x1d, 0xdd,
	0xa4, 0x1d, 0xad, 0xf9, 0x56, 0x33, 0x8d, 0xb3, 0x56, 0x5d, 0x29, 0xa1, 0xb9, 0xda, 0x35, 0xad,
	0x25, 0x6d, 0x52, 0x26, 0x2a, 0xdc, 0xeb, 0x34, 0x8e, 0x8e, 0x3b, 0xb4, 0x65, 0x98, 0x27, 0x5a,
	0x73, 0xec, 0xfe, 0x35, 0xb4, 0xcd, 0xa9, 0xd9, 0x78, 0xa7, 0x71, 0x5b, 0x21, 0xf9, 0x3e, 0x29,
	0x41, 0xfe, 0x9d, 0xf1, 0x41, 0x7e, 0x3e, 0x40, 0x97, 0xfe, 0x22, 0x66, 0x3f, 0x3a, 0x6a, 0xea,
	0xca, 0x3a, 0x59, 0x83, 0x95, 0x37, 0x5a, 0xa7, 0xa3, 0x9b, 0x3f, 0xd3, 0x46, 0xab, 0xde, 0xa8,
	0x69, 0x68, 0xb1, 0x87, 0xc8, 0x3b, 0xd1, 0x5a, 0x67, 0x5a, 0x93, 0xd6, 0x1b, 0x5a, 0x53, 0xf9,
	0x1a, 0x4d, 0xd8, 0x44, 0xc1, 0xf7, 0x86, 0xf9, 0x56, 0x6a, 0x7b, 0x84, 0x2c, 0x74, 0x17, 0xdd,
	0x79, 0x75, 0xb0, 0x7d, 0xfc, 0x8b, 0xf2, 0xed, 0xa6, 0x07, 0x4a, 0xba, 0xe9, 0x47, 0x17, 0xb6,
	0x0c, 0x5a, 0x43, 0x0f, 0x77, 0x7e, 0x3e, 0xc5, 0x68, 0xcc, 0xc3, 0xdd, 0x7a, 0xe7, 0xe4, 0x70,
	0x47, 0xc9, 0x24, 0x3f, 0x77, 0x95, 0x6c, 0xf2, 0x73, 0x4f, 0x59, 0x48, 0x7e, 0xee, 0x2b, 0x8b,
	0x18, 0xa0, 0x28, 0xaa, 0x70, 0x3d, 0x1d, 0xfd, 0x43, 0x87, 0x9e, 0xe8, 0xed, 0xb6, 0x76, 0xa4,
	0x2b, 0x17, 0x9b, 0xff, 0x0e, 0xf9, 0x71, 0xfd, 0xc5, 0xbd, 0x27, 0xc7, 0x26, 0x99, 0x47, 0x81,
	0xa2, 0xa9, 0x1f, 0x9d, 0x35, 0x35, 0x53, 0x20, 0xfc, 0xf4, 0x89, 0xd3, 0x23, 0x80, 0x2c, 0x79,
	0x08, 0xf7, 0x25, 0xf0, 0xbe, 0xd1, 0x39, 0xa6, 0xef, 0x8c, 0x46, 0x4d, 0x17, 0x63, 0x0b, 0x9b,
	0xae, 0x54, 0xcf, 0x83, 0x7b, 0x15, 0x2a, 0x93, 0xb0, 0xd3, 0x9a, 0x9a, 0x79, 0xa2, 0xdc, 0x21,
	0x5f, 0xc1, 0x7a, 0x0a, 0x14, 0x6a, 0xf8, 0x8a, 0x33, 0x64, 0x03, 0x9e, 0xde, 0x3a, 0x2c, 0x67,
	0x31, 0xe8, 0xa1, 0xd1, 0x6c, 0x1a, 0xef, 0x95, 0xec, 0xe6, 0x4f, 0x90, 0x1b, 0xdb, 0x6b, 0x0d,
	0x56, 0xc6, 0xc6, 0xa2, 0x2d, 0xa3, 0x43, 0xdb, 0x3a, 0x1e, 0xf6, 0x32, 0xc0, 0x91, 0x69, 0x9c,
	0x9d, 0x26, 0xca, 0x15, 0x28, 0x72, 0x5f, 0x77, 0x74, 0x81, 0x64, 0x49, 0x11, 0x72, 0x28, 0xc7,
	0xbf, 0x16, 0xce, 0x97, 0xf8, 0xff, 0x11, 0xf6, 0xfe, 0x1e, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xcf,
	0x07, 0x41, 0x5a, 0x1c, 0x00, 0x00,
}
